// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdwmpcbvzfopsvsgcnsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkd21wY2J2emZvcHN2c2djbnNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MzIyNDMsImV4cCI6MjA3MjUwODI0M30.n9PfoaNbbzL2duhE7tUaB3IhVLEZJTjgSDXQnmypEXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});